import type { Category } from '@/types';

export const categories: Category[] = [
  {
    id: '1',
    name: 'Technology',
    slug: 'technology',
    hint: 'tech abstract',
    src: '/images/categories/technology.avif',
  },
  {
    id: '2',
    name: 'Travel',
    slug: 'travel',
    hint: 'world map',
    src: '/images/categories/travel.avif',
  },
  {
    id: '3',
    name: 'Food',
    slug: 'food',
    hint: 'delicious meal',
    src: '/images/categories/food.avif',
  },
  {
    id: '4',
    name: 'Lifestyle',
    slug: 'lifestyle',
    hint: 'modern living',
    src: '/images/categories/lifestyle.avif',
  },
  {
    id: '5',
    name: 'Business',
    slug: 'business',
    hint: 'office meeting',
    src: '/images/categories/business.avif',
  },
  {
    id: '6',
    name: 'Health & Wellness',
    slug: 'health-wellness',
    hint: 'yoga meditation',
    src: '/images/categories/health-wellness.avif',
  },
  {
    id: '7',
    name: 'Finance',
    slug: 'finance',
    hint: 'money coins',
    src: '/images/categories/finance.avif',
  },
  {
    id: '8',
    name: 'Education',
    slug: 'education',
    hint: 'books classroom',
    src: '/images/categories/education.avif',
  },
  {
    id: '9',
    name: 'Arts & Culture',
    slug: 'arts-culture',
    hint: 'art gallery',
    src: '/images/categories/arts-culture.avif',
  },
  {
    id: '10',
    name: 'Sports',
    slug: 'sports',
    hint: 'sports equipment',
    src: '/images/categories/sports.avif',
  },
  {
    id: '11',
    name: 'Science',
    slug: 'science',
    hint: 'lab experiment',
    src: '/images/categories/science.avif',
  },
  {
    id: '12',
    name: 'Home & Garden',
    slug: 'home-garden',
    hint: 'house plant',
    src: '/images/categories/home-garden.avif',
  },
  {
    id: '13',
    name: 'Automotive',
    slug: 'automotive',
    hint: 'sports car',
    src: '/images/categories/automotive.avif',
  },
  {
    id: '14',
    name: 'Pets',
    slug: 'pets',
    hint: 'cute dog',
    src: '/images/categories/pets.avif',
  },
  {
    id: '15',
    name: 'Gaming',
    slug: 'gaming',
    hint: 'game controller',
    src: '/images/categories/gaming.avif',
  },
  {
    id: '16',
    name: 'Productivity',
    slug: 'productivity',
    hint: 'planner desk',
    src: '/images/categories/productivity.avif',
  },
  {
    id: '17',
    name: 'Parenting',
    slug: 'parenting',
    hint: 'parent child',
    src: '/images/categories/parenting.avif',
  },
  {
    id: '18',
    name: 'Photography',
    slug: 'photography',
    hint: 'camera lens',
    src: '/images/categories/photography.avif',
  },
  {
    id: '19',
    name: 'Fashion',
    slug: 'fashion',
    hint: 'stylish outfit',
    src: '/images/categories/fashion.avif',
  },
  {
    id: '20',
    name: 'Entertainment',
    slug: 'entertainment',
    hint: 'movie clapboard',
    src: '/images/categories/entertainment.avif',
  },
];
